# Generated by Django 5.1.2 on 2024-11-05 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_collegestudent_educationorganization_highstudent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='class_rooms',
            field=models.ManyToManyField(to='school.classroom'),
        ),
        migrations.AlterField(
            model_name='college',
            name='grade',
            field=models.CharField(choices=[('lisans', 'lisans'), ('fogh lisans', 'fogh lisans'), ('doktora', 'doktora'), ('fogh doktora', 'fogh doktora')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='major',
            field=models.CharField(choices=[('Riazi', 'Riazi'), ('Ensani', 'Ensani'), ('tajrobi', 'tajrobi')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='masters',
            field=models.ManyToManyField(to='school.master'),
        ),
        migrations.AlterField(
            model_name='college',
            name='students',
            field=models.ManyToManyField(to='school.student'),
        ),
        migrations.AlterField(
            model_name='collegestudent',
            name='education_type',
            field=models.CharField(choices=[('shabane', 'shabane'), ('roozane', 'roozane'), ('pardis khod gardan', 'pardis khod gardan')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='collegestudent',
            name='student_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='collegestudent',
            name='sub_major',
            field=models.CharField(choices=[('bargh', 'bargh'), ('Software Engineering', 'Software Engineering'), ('mohandesi polimer', 'mohandesi polimer'), ('Computer Science', 'Computer Science')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='elementary',
            name='class_room',
            field=models.ManyToManyField(to='school.classroom'),
        ),
        migrations.AlterField(
            model_name='elementary',
            name='students',
            field=models.ManyToManyField(to='school.student'),
        ),
        migrations.AlterField(
            model_name='elementary',
            name='teachers',
            field=models.ManyToManyField(to='school.teacher'),
        ),
        migrations.AlterField(
            model_name='firsthigh',
            name='class_room',
            field=models.ManyToManyField(to='school.classroom'),
        ),
        migrations.AlterField(
            model_name='firsthigh',
            name='students',
            field=models.ManyToManyField(to='school.student'),
        ),
        migrations.AlterField(
            model_name='firsthigh',
            name='teachers',
            field=models.ManyToManyField(to='school.teacher'),
        ),
        migrations.AlterField(
            model_name='highstudent',
            name='major',
            field=models.CharField(choices=[('Riazi', 'Riazi'), ('Ensani', 'Ensani'), ('tajrobi', 'tajrobi')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='master',
            name='salary_per_day',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='master',
            name='working_days',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='secondhigh',
            name='class_room',
            field=models.ManyToManyField(to='school.classroom'),
        ),
        migrations.AlterField(
            model_name='secondhigh',
            name='major',
            field=models.CharField(choices=[('Riazi', 'Riazi'), ('Ensani', 'Ensani'), ('tajrobi', 'tajrobi')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='secondhigh',
            name='students',
            field=models.ManyToManyField(to='school.student'),
        ),
        migrations.AlterField(
            model_name='secondhigh',
            name='teachers',
            field=models.ManyToManyField(to='school.teacher'),
        ),
        migrations.AlterField(
            model_name='snack',
            name='cost',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='salary_per_day',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='working_days',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
